spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: user_service

nginx:
  require-proxy: false

rate-limit:
  ip:
    apply-limit: false

email:
  url: "http://localhost:8080"

web-socket:
  allowed-origin: "http://localhost:8080"

logging:
  level:
    com.korniykom.kotlin_chat: DEBUG