spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 7773
    username: rabbit
    password: password
  application:
    name: kotlin-chat
  datasource:
    url: jdbc:postgresql://localhost:7771/user_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: user_service
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  data:
    redis:
      username: "default"
      host: localhost
      port: 7772
      timeout: 2000

jwt:
  secret: M2I4OTA0d3k0dXRldGg3ODg4eWlzZWk3dXQ3eThldGdodWllcmZnaHVmZHZiamh2ZGZuamtld2l1OHVldTkwaG9ob2loOThnaHVuaiBqa3NlaGYwMDl1d2p3cmowOTBqOXd0M2hpaDl3OHQ0ODk=
  expiration-minutes: 15

email:
  from: korniykom@gmail.com
  verification:
    expiry-hours: 24
  reset-password:
    expiry-minutes: 15

nginx:
  trusted-ips:
    - "127.0.0.1"
    - "::1"
    - "172.17.0.0/16"
    - "10.0.0.5/32"


