spring:
  jpa:
    hibernate:
      ddl-auto: validate

nginx:
  require-proxy: true


rate-limit:
  ip:
    apply-limit: true

email:
  url: "domain-to-deploy-project.com"

web-socket:
  allowed-origin: "domain-to-deploy-project.com"