spring:
  application:
    name: kotlin-chat
  datasource:
    url: jdbc:postgresql://localhost:7771/user_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  data:
    redis:
      username: "default"
      host: localhost
      port: 7772
      timeout: 2000

jwt:
  secret: M2I4OTA0d3k0dXRldGg3ODg4eWlzZWk3dXQ3eThldGdodWllcmZnaHVmZHZiamh2ZGZuamtld2l1OHVldTkwaG9ob2loOThnaHVuaiBqa3NlaGYwMDl1d2p3cmowOTBqOXd0M2hpaDl3OHQ0ODk=
  expiration-minutes: 15

email:
  verification:
    expiry-hours: 24
  reset-password:
    expiry-minutes: 15

nginx:
  trusted-ips:
    - "127.0.0.1"
    - "::1"
    - "172.17.0.0/16"
    - "10.0.0.5/32"